server:
  port: 8090

spring:
  data:
    mongodb:
      username: misha
      password: misha
      host: localhost
      port: 27018
      database: customer
      authentication-database: admin
  config:
    import: optional:configserver:http://localhost:8888
